### ISSUE TITLE
Update breaks Shortcode plugin!

### ISSUE THREAD

**Issue by axel-rank** [Sommerregen/grav-plugin-textformatter#3]
Hi, latest Update to Text Formatter 1.1.0 broke nearly my whole Homepage!
Section Shortcode isn't rendered anymore. Embedding audio using HTML5 audio element doesn't work anymore. Using `<br/>`for linebreaks doesn't work anymore. 
So a lot of stuff doesn't work anymore!

**Comment by Sommerregen** [comment]
@axel-rank TextFormatter plugin interferes with [Grav Shortcode Core plugin](https://github.com/getgrav/grav-plugin-shortcode-core) in some way, when `bbcodes.enabled: true`. I haven't tested it, but I guess TextFormatter parses the markdown file first and then the Shortcode Core plugin with its extensions. You may need setting the `bbcodes.enabled` option to false (https://github.com/Sommerregen/grav-plugin-textformatter/blob/develop/textformatter.yaml#L22).

I guess in your case you did the change in `user/plugins/textformatter/textformatter.yaml`, but due to the update it was overridden. Please make sure you are always doing your changes in your `user/config/plugins` folder.

Please report back, when the issue still persists. As for the update it [hasn't changed the way how BBcode is handled](https://github.com/Sommerregen/grav-plugin-textformatter/blob/develop/classes/TextFormatter.php#L170-L189).

**Comment by axel-rank** [comment]
I disabled bbcodes in Admin --> nothing changed, still the same. Only deactivation of textformatter helps.

**Comment by Sommerregen** [comment]
@axel-rank The thing is; I haven't changed the way how TextFormatter processes BBCodes. If it breaks your site, it did it also with the previous version. And setting `bbcodes.enabled: false` should bypass the parsing of those codes by TextFormatter...

So, I guess there will be something more. Can you give me a minimal example to recreate the issue?

**Comment by axel-rank** [comment]
Well, Textformatter was installed and enabled and everything was ok and I didn't use bbcodes at all.
Only simple html (see my first post) and the [section shortcode](https://github.com/getgrav/grav-plugin-shortcode-core#section) of the shortcode-core plugin. 
Meanwhile I uninstalled Textformatter as I wasn't using it at all. It was just installed and activated.
So maybe I will try it local in later versions, but in the moment I have no time for digging deeper (sorry).

**Comment by Sommerregen** [comment]
Hi @axel-rank ,

I tested my plugin and changed some lines. Don't know if it helps. I'll close this issue here since more information are needed. If the issue still persists, reopen it.
